version: "3"

services:
  node-one:
    image: node-one:1
    build:
      context: ./
      dockerfile: DockerFileNode1
    volumes:
      - /data/springboot-docker-compose-app
    ports:
      - "172.17.87.180:8080:8080"
    networks:
      network:
        ipv4_address: 10.5.0.5

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1